# Generated by Django 6.0.3 on 2026-03-05 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_initial'),
        ('organizations', '0003_alter_membership_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['organization'], name='activity_ac_organiz_a8fe4b_idx'),
        ),
    ]
