# Task statuses
TASK_STATUS_TODO = "TODO"
TASK_STATUS_IN_PROGRESS = "IN_PROGRESS"
TASK_STATUS_DONE = "DONE"

# Roles
ROLE_ADMIN = "ADMIN"
ROLE_MANAGER = "MANAGER"
ROLE_DEVELOPER = "DEVELOPER"
ROLE_VIEWER = "VIEWER"