# Generated by Django 6.0.3 on 2026-03-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_c291d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_is_read_9edb86_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
